# Generated by Django 3.1 on 2020-09-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nfce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField()),
                ('data_alteracao', models.DateTimeField(blank=True)),
                ('empresa', models.IntegerField()),
                ('pdv', models.IntegerField()),
                ('data_ocorrencia', models.DateField()),
                ('num_sat', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=200)),
                ('num_extrato', models.IntegerField()),
                ('num_ticket', models.IntegerField()),
                ('atendente', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'usr_t_nfce_inutilizada',
                'managed': False,
            },
        ),
    ]
